### ISSUE TITLE
check_content_type got removed from upload event workload by accident

### ISSUE THREAD

**Issue by alanpoole** [gfilicetti/gke-github-deployment#52]
https://github.com/gfilicetti/gke-github-deployment/tree/main/workflows

```
        - check_content_type:
            switch:
                - condition: ${not text.match_regex(contentType, "video") and not text.match_regex(contentType, "octet-stream")}
                  return: ${"Media " + contentType + " not valid."}
                  next: end
            next: prep_transcoding_job
```
