### ISSUE TITLE
Increase requested CPU/Memory on a GKE Job as a starting point

### ISSUE THREAD

**Issue by alanpoole** [gfilicetti/gke-github-deployment#58]
Workflow: upload-event-gcs-gcp-transcoding

```
                        resources:
                            requests:
                                cpu: 16
                                memory: 64Gi
```
